### ISSUE TITLE
Clarify role and need for both pm and qa issue trackers

### ISSUE THREAD

**Issue by rufuspollock** [datahq/pm#255]
We have both QA and PM issue trackers and it is a bit confusing: which should you use, and for what?

TODO: user stories

## User Stories

As Someone who has spotted a bug I want to know where I post it so that I can submit it and it can get fixed

As Someone who has a feature idea I want to know where I post so that I can share it and get it improved

**Comment by zelima** [comment]
The short and simple answer would be that QA repo is user-oriented, while PM repo is more for internal use. 

- QA is for registering the bugs/questions/ideas for https://datahub.io/ or data tools like CLI
- PM is organized by us (project managers, scrum masters, developers etc...), so that we know on which Epic we are exactly working on, how are we going to solve and when.

Issue registered in QA will ultimately become an issue in PM (if it's big enough), with analysis, task lists, and acceptance criteria.

**Comment by zelima** [comment]
Think is fine to close this as FIXED
