### ISSUE TITLE
Trial A/B testing on frontend

### ISSUE THREAD

**Issue by rufuspollock** [datahq/pm#76]
As a Product Owner I want to experiment with different language and features so that I know what works best (in a rigorous way)

## Tasks

* [x] Research methods of doing this
* [x] Trial this on one page (e.g. language on pricing page)

## Research

* Google experiments: https://developers.google.com/analytics/solutions/experiments
  * https://www.google.com/analytics/optimize/features/
* https://github.com/omichelsen/express-ab
* Optimizely etc

**Comment by anuveyatsu** [comment]
Have implemented A/B testing for front page (see https://github.com/datahq/frontend/issues/154) using Google Experiments + Express-ab library, see commit for more details - https://github.com/datahq/frontend/commit/855fc27a99b6f18f8b4aa7ed4294a8042f18a03e

We'll analyse results in few days when any data is available on GA.

**Comment by rufuspollock** [comment]
@anuveyatsu can you add more of a summary of what the options (how you rated them) and  and how this works  (so that others could implement and how we evaluate).

**Comment by anuveyatsu** [comment]
@rufuspollock here is a comparison of Google Optimize vs Convert vs VWO vs Optimizely

The main advantage of Google's product is that they offer a free solution. But they also have a more powerful paid version of Google Optimize. All other alternatives offer only free trials. 

Another advantage is ease of integration as we already have GA + server-side rendering. E.g., VWO offers only in-browser solution which might result to slower performance for clients. 

VWO suggest that Google Optimize wouldn't work only in Chrome, however, I don't think it is the case since we're using server-side solution (will double check).

Comparison tables:
https://www.convert.com/compare-google-optimize-convert-experiences/
https://vwo.com/comparison/google-optimize/ (bottom of page)
https://vwo.com/comparison/optimizely/ (bottom of page)

**Comment by anuveyatsu** [comment]
Before closing this issue I need to re-implement Experiments in Google Optimize instead of in GA.

**Comment by anuveyatsu** [comment]
FIXED using Google Optimize
